config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 

	resources :user_resources, :studios
	devise_for :users

	root 'landing#index'

	get '/login' => 'login#index'
	get '/join' => 'login#join'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/studio.rb
class Studio < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_resource.rb
class UserResource < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update) {
			|u| u.permit(
				:name, :email, :password, :current_password,
				:addr1, :addr2, :phone, :email, :bnum, :base_rate, :closing) }
	end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	def index
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index
	end
	def join
	end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
	before_action :set_studio, only: [:show, :edit, :update, :destroy]

	# GET /studios
	# GET /studios.json
	def index
		@studios = Studio.all
	end

	# GET /studios/1
	# GET /studios/1.json
	def show
	end

	# GET /studios/new
	def new
		@studio = Studio.new
	end

	# GET /studios/1/edit
	def edit
	end

	# POST /studios
	# POST /studios.json
	def create
		@studio = Studio.new(studio_params)

		respond_to do |format|
			if @studio.save
				format.html { redirect_to @studio, notice: 'Studio was successfully created.' }
				format.json { render :show, status: :created, location: @studio }
			else
				format.html { render :new }
				format.json { render json: @studio.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /studios/1
	# PATCH/PUT /studios/1.json
	def update
		respond_to do |format|
			if @studio.update(studio_params)
				format.html { redirect_to @studio, notice: 'Studio was successfully updated.' }
				format.json { render :show, status: :ok, location: @studio }
			else
				format.html { render :edit }
				format.json { render json: @studio.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /studios/1
	# DELETE /studios/1.json
	def destroy
		@studio.destroy
		respond_to do |format|
			format.html { redirect_to studios_url, notice: 'Studio was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_studio
			@studio = Studio.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def studio_params
			params.require(:studio).permit(:name, :addr1, :addr2, :phone)
		end
end

app/controllers/user_resources_controller.rb
class UserResourcesController < ApplicationController
	before_action :set_user_resource, only: [:show, :edit, :update, :destroy]

	# GET /user_resources
	# GET /user_resources.json
	def index
		@user_resources = UserResource.all
	end

	# GET /user_resources/1
	# GET /user_resources/1.json
	def show
	end

	# GET /user_resources/new
	def new
		@user_resource = UserResource.new
	end

	# GET /user_resources/1/edit
	def edit
	end

	# POST /user_resources
	# POST /user_resources.json
	def create
		@user_resource = UserResource.new(user_resource_params)

		respond_to do |format|
			if @user_resource.save
				format.html { redirect_to @user_resource, notice: 'User resource was successfully created.' }
				format.json { render :show, status: :created, location: @user_resource }
			else
				format.html { render :new }
				format.json { render json: @user_resource.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /user_resources/1
	# PATCH/PUT /user_resources/1.json
	def update
		respond_to do |format|
			if @user_resource.update(user_resource_params)
				format.html { redirect_to @user_resource, notice: 'User resource was successfully updated.' }
				format.json { render :show, status: :ok, location: @user_resource }
			else
				format.html { render :edit }
				format.json { render json: @user_resource.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /user_resources/1
	# DELETE /user_resources/1.json
	def destroy
		@user_resource.destroy
		respond_to do |format|
			format.html { redirect_to user_resources_url, notice: 'User resource was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_user_resource
			@user_resource = UserResource.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def user_resource_params
			params.require(:user_resource).permit(:user_id, :url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/user_resources_helper.rb
module UserResourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/landing/index.html.erb
<%# content_for :view_specific_css do %>
	<%#= stylesheet_link_tag "whatever" %>
<%# end %>

<div class="ink-grid">
	<!--[if lte IE 9 ]>
	<div class="ink-alert basic" role="alert">
		<button class="ink-dismiss">&times;</button>
		<p><strong>You are using an outdated Internet Explorer version.</strong>
			Please <a href="http://browsehappy.com/">upgrade to a modern browser</a> to improve your web experience.</p>
	</div>
	-->

	<header class="vertical-space">
		<h1>ShiftShark<small>test test</small></h1>
		<nav class="ink-navigation">
			<ul class="menu horizontal black">
				<li class="active"><a href="#">item</a></li>
				<li><a href="#">item</a></li>
				<li><a href="#">item</a></li>
			</ul>
		</nav>
	</header>
	<div class="column-group gutters">
		<div class="all-100">
			<h2>heading</h2>
			<img data-src="holder.js/1650x928/auto/ink" alt="">
		</div>
	</div>
	<div class="column-group gutters">
		<div class="all-50 small-100 tiny-100">
			<h3>heading</h3>
			<img data-src="holder.js/1200x600/auto/ink" alt="">
			<p class="quarter-top-space">"Red is not the right word," was the reply. "The plague was scarlet.  The whole face and body turned scarlet in an hour's time. Don't I  know? Didn't I see enough of it? And I am telling you it was scarlet  because&mdash;well, because it was scarlet. There is no other word for it."</p>
		</div>
		<div class="all-50 small-100 tiny-100">
			<h3>heading</h3>
			<img data-src="holder.js/1200x600/auto/ink" alt="">
			<p class="quarter-top-space">"Red is not the right word," was the reply. "The plague was scarlet.  The whole face and body turned scarlet in an hour's time. Don't I  know? Didn't I see enough of it? And I am telling you it was scarlet  because&mdash;well, because it was scarlet. There is no other word for it."</p>
		</div>
	</div>
</div>
<footer class="clearfix">
	<div class="ink-grid">
		<ul class="unstyled inline half-vertical-space">
			<li class="active"><a href="#">About</a></li>
			<li><a href="#">Sitemap</a></li>
			<li><a href="#">Contacts</a></li>
		</ul>
		<p class="note">Identification of the owner of the copyright, either by name, abbreviation, or other designation by which it is generally known.</p>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<!-- meta -->
		<title>ShiftShark</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

		<!-- icon -->
		<%= favicon_link_tag 'favicon.ico' %>

		<!-- css -->
		<%= stylesheet_link_tag 'application-all', media: 'all',
			'data-turbolinks-track': 'reload' %>
		<!--[if lte IE 8]>
			<%= stylesheet_link_tag "application-ie", :media => "all", '
				data-turbolinks-track': 'reload' %>
		<![endif]-->
		<%= yield :view_specific_css %>

		<!-- js -->
		<%= javascript_include_tag 'application',
			'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<!--<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>-->
		<%= yield %>
	</body>
</html>

app/views/login/index.html.haml
%link{:rel => "stylesheet", :type => "text/css", :href => "/css/login.css"}

.ink-grid
	/[if lte IE 9]
		.ink-alert.basic{ role:"alert"}
			%button.ink-dismiss &times;
			%p
				%strong You are using an outdated Internet Explorer version.</strong>
				Please
				%a{ href: "http://browsehappy.com/"} upgrade to a modern browser</a>
				to improve your web experience.

	.column-group.quarter-gutters.align-center.vertical-space
		.all-25
		.all-20.vertical-space.tiny-100
			%img( data-src="holder.js/1200x600/auto/ink" alt="")
		.all-5
		.all-25.vertical-space.verticalLine
			%h3 Welcoming Text
			%p Welcome to ShiftShark :)
			%p We're making scheduling and invoice tools for yoga teachers and studio managers.
			.column-group.quarter-gutters
				.all-20
				.all-25
					%button.ink-button.black Login
				.all-10
				.all-25
					%button.ink-button.blue Signup
				.all-20
		.all-25

%footer.clearfix
	.ink-grid
		%ul.unstyled.inline.half-vertical-space
			%li.active
				%a( href="#") linkielink
			%li
				%a( href="#") linkielink
			%li
				%a( href="#") linkielink
		%p.note copyright text copyright text copyright text

app/views/login/join.html.haml
.ink-grid
	/[if lte IE 9]
		.ink-alert.basic{ role:"alert"}
			%button.ink-dismiss &times;
			%p
				%strong You are using an outdated Internet Explorer version.</strong>
				Please
				%a{ href: "http://browsehappy.com/"} upgrade to a modern browser</a>
				to improve your web experience.

	%header.vertical-space
		%h1
			ShiftShark
			%small test test
		%nav.ink-navigation
			%ul.menu.horizontal.black
				%li.active
					%a( href="#") item
				%li
					%a( href="#") item
				%li
					%a( href="#") item

	.column-group.gutters
		.all-100
			%h2 heading
			%img( data-src="holder.js/1650x928/auto/ink" alt="")

	.column-group.gutters
		.all-50.small-100.tiny-100
			%h3 heading
			%img( data-src="holder.js/1200x600/auto/ink" alt="")
			%p.quarter-top-space "Red is not the right word," was the reply. "The plague was scarlet.  The whole face and body turned scarlet in an hour's time. Don't I  know? Didn't I see enough of it? And I am telling you it was scarlet  because&mdash;well, because it was scarlet. There is no other word for it."

		.all-50.small-100.tiny-100
			%h3 heading
			%img( data-src="holder.js/1200x600/auto/ink" alt="")
			%p.quarter-top-space "Red is not the right word," was the reply. "The plague was scarlet.  The whole face and body turned scarlet in an hour's time. Don't I  know? Didn't I see enough of it? And I am telling you it was scarlet  because&mdash;well, because it was scarlet. There is no other word for it."

%footer.clearfix
	.ink-grid
		%ul.unstyled.inline.half-vertical-space
			%li.active
				%a( href="#") About
			%li
				%a( href="#") Sitemap
			%li
				%a( href="#") Contacts
		%p.note Identification of the owner of the copyright, either by name, abbreviation, or other designation by which it is generally known.

app/views/studios/_form.html.erb
<%= form_for(studio) do |f| %>
  <% if studio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
      <% studio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :addr1 %>
    <%= f.text_field :addr1 %>
  </div>

  <div class="field">
    <%= f.label :addr2 %>
    <%= f.text_field :addr2 %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studios/edit.html.erb
<h1>Editing Studio</h1>

<%= render 'form', studio: @studio %>

<%= link_to 'Show', @studio %> |
<%= link_to 'Back', studios_path %>

app/views/studios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Addr1</th>
      <th>Addr2</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studios.each do |studio| %>
      <tr>
        <td><%= studio.name %></td>
        <td><%= studio.addr1 %></td>
        <td><%= studio.addr2 %></td>
        <td><%= studio.phone %></td>
        <td><%= link_to 'Show', studio %></td>
        <td><%= link_to 'Edit', edit_studio_path(studio) %></td>
        <td><%= link_to 'Destroy', studio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studio', new_studio_path %>

app/views/studios/new.html.erb
<h1>New Studio</h1>

<%= render 'form', studio: @studio %>

<%= link_to 'Back', studios_path %>

app/views/studios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @studio.name %>
</p>

<p>
  <strong>Addr1:</strong>
  <%= @studio.addr1 %>
</p>

<p>
  <strong>Addr2:</strong>
  <%= @studio.addr2 %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @studio.phone %>
</p>

<%= link_to 'Edit', edit_studio_path(@studio) %> |
<%= link_to 'Back', studios_path %>

app/views/user_resources/_form.html.erb
<%= form_for(user_resource) do |f| %>
  <% if user_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_resource.errors.count, "error") %> prohibited this user_resource from being saved:</h2>

      <ul>
      <% user_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_resources/edit.html.erb
<h1>Editing User Resource</h1>

<%= render 'form', user_resource: @user_resource %>

<%= link_to 'Show', @user_resource %> |
<%= link_to 'Back', user_resources_path %>

app/views/user_resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Resources</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_resources.each do |user_resource| %>
      <tr>
        <td><%= user_resource.user_id %></td>
        <td><%= user_resource.url %></td>
        <td><%= link_to 'Show', user_resource %></td>
        <td><%= link_to 'Edit', edit_user_resource_path(user_resource) %></td>
        <td><%= link_to 'Destroy', user_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Resource', new_user_resource_path %>

app/views/user_resources/new.html.erb
<h1>New User Resource</h1>

<%= render 'form', user_resource: @user_resource %>

<%= link_to 'Back', user_resources_path %>

app/views/user_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_resource.user_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @user_resource.url %>
</p>

<%= link_to 'Edit', edit_user_resource_path(@user_resource) %> |
<%= link_to 'Back', user_resources_path %>